<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-08T15:23:09 ICT" name="Default suite" finished-at="2023-08-08T15:23:09 ICT" duration-ms="41">
    <groups>
    </groups>
    <test started-at="2023-08-08T15:23:09 ICT" name="Default test" finished-at="2023-08-08T15:23:09 ICT" duration-ms="41">
      <class name="SanPhamTestProvider">
        <test-method is-config="true" signature="setUp()[pri:0, instance:SanPhamTestProvider@9f116cc]" started-at="2023-08-08T15:23:09 ICT" name="setUp" finished-at="2023-08-08T15:23:09 ICT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TestInsert(java.lang.String,java.lang.String,java.lang.Long,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:SanPhamTestProvider@9f116cc]" started-at="2023-08-08T15:23:09 ICT" name="TestInsert" data-provider="db" finished-at="2023-08-08T15:23:09 ICT" duration-ms="6" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void SanPhamTestProvider.TestInsert(java.lang.String,java.lang.String,java.lang.Long,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TestInsert([java.lang.String arg0, java.lang.String arg1, java.lang.Long arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5])
Arguments: [(java.lang.String) TS004,(java.lang.String) Rau Má Đậu Xanh,(java.lang.Integer) 25000,(java.lang.String) LSP07,(java.lang.String) nho.jpg,(java.lang.String) abc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void SanPhamTestProvider.TestInsert(java.lang.String,java.lang.String,java.lang.Long,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TestInsert([java.lang.String arg0, java.lang.String arg1, java.lang.Long arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5])
Arguments: [(java.lang.String) TS004,(java.lang.String) Rau Má Đậu Xanh,(java.lang.Integer) 25000,(java.lang.String) LSP07,(java.lang.String) nho.jpg,(java.lang.String) abc]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInsert -->
      </class> <!-- SanPhamTestProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
